pluginManagement { includeBuild('../node_modules/@react-native/gradle-plugin') }
includeBuild('../node_modules/@react-native/gradle-plugin')
rootProject.name = 'S22Updater'
include ':app'
include ':react-native-svg'
project(':react-native-svg').projectDir = file('../node_modules/react-native-svg/android')
